- 数组(矩阵)与数的运算
- - 数组与数组的运算
- - 数组中的轴
- 常见统计函数
- 其他操作

## 1.数组(矩阵)与数的运算

#### 形状相同的矩阵运算,运算结果与原矩阵形状相同

In [28]:
import numpy as np

In [29]:
arr1=np.arange(10,22).reshape(3,4)
arr2=np.arange(1,13).reshape(3,4)
print('arr1:',arr1)
print('arr2:',arr2)
print('加法','-'*30)
print(arr1+arr2)
print('减法','-'*30)
print(arr1-arr2)
print('乘法','-'*30)
print(arr1*arr2)
print('除法','-'*30)
print((arr1 / arr2).astype(int))


arr1: [[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]]
arr2: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
加法 ------------------------------
[[11 13 15 17]
 [19 21 23 25]
 [27 29 31 33]]
减法 ------------------------------
[[9 9 9 9]
 [9 9 9 9]
 [9 9 9 9]]
乘法 ------------------------------
[[ 10  22  36  52]
 [ 70  90 112 136]
 [162 190 220 252]]
除法 ------------------------------
[[10  5  4  3]
 [ 2  2  2  2]
 [ 2  1  1  1]]


#### 形状不同

##### 1.形状不同, 运行出错

In [30]:
arr3=np.arange(1,5).reshape(2,2)
print(arr3)
arr4=np.arange(1,5).reshape(4,1)
print(arr4)
print('运算会出错')
# print(arr3+arr4)

[[1 2]
 [3 4]]
[[1]
 [2]
 [3]
 [4]]
运算会出错


##### 2.形状不同, 行/列 相同可运行

In [31]:
# 形状不同但行数相同，可以广播相加
arr3 = np.arange(1, 11).reshape(2, 5)
print(arr3)
arr4 = np.arange(1, 7).reshape(2, 3)  # 列数不同，但行数相同
print(arr4)
print('-' * 30)
# 为了相加，需要将 arr4 扩展为与 arr3 相同的列数
# 这里演示通过拼接方式使列数一致
arr4_padded = np.hstack([arr4, np.zeros((2, 2))])  # 补零到 2x5
print(arr3 + arr4_padded)



[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
[[1 2 3]
 [4 5 6]]
------------------------------
[[ 2.  4.  6.  4.  5.]
 [10. 12. 14.  9. 10.]]


In [32]:
# 形状不同，列相同可运行
arr4 = np.arange(1, 7).reshape(2, 3)
print(arr4)
print('-' * 30)
arr5 = np.arange(1, 4).reshape(1, 3)  # 改为列相同形状 (1,3)
print(arr5)
print('-' * 30)
print(arr4 + arr5)

[[1 2 3]
 [4 5 6]]
------------------------------
[[1 2 3]]
------------------------------
[[2 4 6]
 [5 7 9]]


## 2. 常用统计函数

In [33]:
import numpy as np

In [40]:
arr8=np.arange(0,12).reshape(3,4)
print(arr8)
print('-'*30)
print("数组的和:",arr8.sum())
#按轴求和
print("按轴求和(axis=0)↓:",arr8.sum(axis=0))#按列求和
print("按轴求和(axis=1)→:",arr8.sum(axis=1))#按行求和

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------------------------
数组的和: 66
按轴求和(axis=0)↓: [12 15 18 21]
按轴求和(axis=1)→: [ 6 22 38]


In [43]:
#求最小值
print("数组的最小值:",arr8.min())
#按轴求最小值
print("按轴求最小值(axis=0)↓:",arr8.min(axis=0))#按列求最小值
print("按轴求最小值(axis=1)→:",arr8.min(axis=1))#按行求最小值
print('-'*30)
#求最大值
print("数组的最大值:",arr8.max())
#按轴求最大值
print("按轴求最大值(axis=0)↓:",arr8.max(axis=0))#按列求最大值
print("按轴求最大值(axis=1)→:",arr8.max(axis=1))#按行求最大值

数组的最小值: 0
按轴求最小值(axis=0)↓: [0 1 2 3]
按轴求最小值(axis=1)→: [0 4 8]
------------------------------
数组的最大值: 11
按轴求最大值(axis=0)↓: [ 8  9 10 11]
按轴求最大值(axis=1)→: [ 3  7 11]


In [46]:
print(arr8)
print('-'*30)
print("数组的累计和:",arr8.cumsum())#按元素累加,并展平
print('-'*30)
print("数组的累计和:",arr8.cumsum(axis=1))#按行累加


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------------------------
数组的累计和: [ 0  1  3  6 10 15 21 28 36 45 55 66]
------------------------------
数组的累计和: [[ 0  1  3  6]
 [ 4  9 15 22]
 [ 8 17 27 38]]


In [58]:
arr9=np.arange(13,25).reshape(3,4)
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [ ]:
arr9=np.arange().reshape(3,4).random()
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


In [63]:
arr9=np.arange(13,25).reshape(3,4)
print(arr9)
print('-'*30)
#求最小值下标
print("数组的最小值下标:",arr9.argmin())
print('-'*30)
#求最大值下标
print("数组的最大值下标:",arr9.argmax())
#按轴求最小索引
print("按轴求最小索引:",arr9.argmin(axis=0))
print("按轴求最小索引:",arr9.argmin(axis=1))

[[13 14 15 16]
 [17 18 19 20]
 [21 22 23 24]]
------------------------------
数组的最小值下标: 0
------------------------------
数组的最大值下标: 11
按轴求最小索引: [0 0 0 0]
按轴求最小索引: [0 0 0]


## 3. 其他操作

In [ ]:
import numpy as np

### 3.1数组的添加

In [71]:
# 数组的添加
#1. 垂直添加
arr11=np.arange(1,5).reshape(2,2)
print(arr11)
print('-'*30)
arr12=np.arange(5,9).reshape(2,2)
print(arr12)
print('-'*30)
#垂直添加(按行添加)
print("垂直添加(按行添加):")
print(np.vstack((arr11,arr12)))
print('-'*30)
#2. 水平添加
print("水平添加(按列添加):")
print(np.hstack((arr11,arr12)))

[[1 2]
 [3 4]]
------------------------------
[[5 6]
 [7 8]]
------------------------------
垂直添加(按行添加):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
------------------------------
水平添加(按列添加):
[[1 2 5 6]
 [3 4 7 8]]


In [72]:
#数组删除
arr12=np.arange(0,12).reshape(3,4)
print(arr12)
print('-'*30)
#删除第2行
print("删除第2行:")
print(np.delete(arr12,1,axis=0))
print('-'*30)
#删除第2列
print("删除第2列:")
print(np.delete(arr12,1,axis=1))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
------------------------------
删除第2行:
[[ 0  1  2  3]
 [ 8  9 10 11]]
------------------------------
删除第2列:
[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [87]:
#数组去重
arr12=np.array([1,2,3,4,5,6,7,8,9,10,1,2,3,4,5,6,7,8,9,10])
print("arr12:",arr12)
print('-'*30)
print("去重后的数组:")
print(np.unique(arr12))
print('-'*30)

arr13=np.array([[1,2,3,4,5,6,7,8,9,10],[1,2,3,4,5,6,7,8,9,10]])
print("arr13:",arr13)
print('-'*30)
print("去重后的数组的索引:")
print("axis=0:",np.unique(arr13,return_index=True,axis=0))
print("axis=1:",np.unique(arr13,return_index=True,axis=1))


arr12: [ 1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10]
------------------------------
去重后的数组:
[ 1  2  3  4  5  6  7  8  9 10]
------------------------------
arr13: [[ 1  2  3  4  5  6  7  8  9 10]
 [ 1  2  3  4  5  6  7  8  9 10]]
------------------------------
去重后的数组的索引:
axis=0: (array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), array([0]))
axis=1: (array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))


### 3.2数组拼接与堆叠

#### 拼接与堆叠的区别“: 拼接不增加维度，堆叠增加维度”


拼接

In [98]:
import numpy as np
arr14=np.array([[1,2,3],[4,5,6]])
arr15=np.array([[7,8,9],[10,11,12]])

In [100]:
print("arr14:",arr14)
print("arr15:",arr15)
#默认情况下，数组的拼接是在axis=0方向上进行的，即垂直拼接
print("默认情况下,垂直拼接:")
print(np.concatenate((arr14,arr15)))
#指定axis=1,水平拼接
print("指定axis=1,水平拼接:")
print(np.concatenate((arr14,arr15),axis=1))


arr14: [[1 2 3]
 [4 5 6]]
arr15: [[ 7  8  9]
 [10 11 12]]
默认情况下,垂直拼接:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
指定axis=1,水平拼接:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


堆叠

In [111]:
### 3.3数组的拼接与堆叠
# 拼接
# np.concatenate((arr14,arr15))
print("arr14:",arr14)
print("arr15:",arr15)
# 堆叠
#默认情况下，数组的堆叠是在axis=0方向上进行的，即垂直堆叠
s1=np.stack((arr14,arr15))
print("垂直堆叠:\n",s1)
print("垂直堆叠形状:",s1.shape)
# 水平堆叠
s2=np.stack((arr14,arr15),axis=1)
print("水平堆叠:\n",s2)
print("水平堆叠形状:",s2.shape)


arr14: [[1 2 3]
 [4 5 6]]
arr15: [[ 7  8  9]
 [10 11 12]]
垂直堆叠:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
垂直堆叠形状: (2, 2, 3)
水平堆叠:
 [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
水平堆叠形状: (2, 2, 3)


In [ ]:
#二维数组堆叠
a=np.array([[1,2,3],[4,5,6]])
print(a)
print('-'*30)
b=np.array([[7,8,9],[10,11,12]])
print(b)


[[1 2 3]
 [4 5 6]]
------------------------------
[[ 7  8  9]
 [10 11 12]]


In [119]:
s3=np.stack((a,b))
print("垂直堆叠:\n",s3)
print("垂直堆叠形状:",s3.shape)
print('-'*30)
# 水平堆叠
s4=np.stack((a,b),axis=1)
print("水平堆叠:\n",s4)
print("水平堆叠形状:",s4.shape)

垂直堆叠:
 [[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
垂直堆叠形状: (2, 2, 3)
------------------------------
水平堆叠:
 [[[ 1  2  3]
  [ 7  8  9]]

 [[ 4  5  6]
  [10 11 12]]]
水平堆叠形状: (2, 2, 3)


### 3.3数组的分割

In [ ]:
arr16=np.arange(0,12).reshape(3,4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [122]:
print(arr16)

#切割
print("垂直切割:",np.split(arr16,3))#垂直切割
print("水平切割:",np.split(arr16,4,axis=1))#水平切割

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
垂直切割: [array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]
水平切割: [array([[0],
       [4],
       [8]]), array([[1],
       [5],
       [9]]), array([[ 2],
       [ 6],
       [10]]), array([[ 3],
       [ 7],
       [11]])]


### 3.4 数组的转置与轴滚动

#### 1.转置

In [ ]:
arr17=np.arange(0,12).reshape(3,4)
print(arr17)
arr18=arr17.T
print("转置1:",arr18)
arr19=arr17.swapaxes(0,1)#交换轴(0轴和1轴)
print("转置2:",arr19)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
转置1: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
转置2: [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]


#### 2.滚动

In [140]:
print(arr17)
print("1滚动轴(1轴到0轴):")
arr20 = np.rollaxis(arr17, 1, 0)
print(arr20)
print('-'*30)

arr21=np.ones((3,4))#创建一个3行4列的数组,元素全为1
print(arr21)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
1滚动轴(1轴到0轴):
[[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


## 4数组中特殊值

In [141]:
import numpy as np

In [143]:
a=np.inf
print(a)

b=np.nan
print(b)

c=np.NAN
print(c)

d=-np.inf
print(d)

inf
nan
nan
-inf


In [147]:
np.inf==np.inf

True

In [148]:
np.nan==np.nan

False