In [16]:
import time

a=5
print(a)
#当前时间戳
time.time()#从1970年1月1日00:00:00开始按秒计算的偏移量


5


1771811587.63106

In [17]:
#转换时间格式
time.strftime("%Y-%m-%d %H:%M:%S", time.localtime())

'2026-02-23 09:53:07'

In [35]:
import numpy as np
#编写zip例子
list1=[1,2,3,4,5]
list2=[6,7,8,9,10]
result=zip(list1,list2)#将两个列表打包成元组
print(result)
print(list(result))

print('-'*30,'\nnumpy')
array1=np.array(list1)
array2=np.array(list2)
# print(array1)
# print(array2)
result2=array1+array2#数组元素对应相加
result3=np.concatenate((array1,array2))#数组拼接
result4=np.column_stack((array1,array2))#数组拼接(按列拼接)
result5=np.row_stack((array1,array2))#数组拼接(按行拼接)
print('-'*30,'\n',result2)
print('-'*30,'\n',result3)
print('-'*30,'\n',result4)
print('-'*30,'\n',result5)


[(1, 6), (2, 7), (3, 8), (4, 9), (5, 10)]
------------------------------ 
numpy
------------------------------ 
 [ 7  9 11 13 15]
------------------------------ 
 [ 1  2  3  4  5  6  7  8  9 10]
------------------------------ 
 [[ 1  6]
 [ 2  7]
 [ 3  8]
 [ 4  9]
 [ 5 10]]
------------------------------ 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:
import numpy as np
import time

# 列表处理1000万个数字的加法(慢,需循环)
time1=time.time()
list1=[i for i in range(1000000)]
list1=[i*2 for i in range(1000000)]
result=[a+b for a,b in zip(list1,list2)]
end=time.time()
print(f"列表处理1000万个数字的加法耗时:{end-time1}")
time2=time.time()
print('-'*30,'\numpy处理1000万个数字的加法')
arr1=np.arange(1000000)
arr2=np.arange(1000000)
result=arr1+arr2
end=time.time()
print(f"numpy处理1000万个数字的加法耗时:{end-time2}")


列表处理1000万个数字的加法耗时:0.08752107620239258
------------------------------ 
umpy处理1000万个数字的加法
numpy处理1000万个数字的加法耗时:0.004021167755126953


In [ ]:
print("list to array",'-'*30,)
list1=[1,2,3,4,5]
arr0=np.array(list1)
print(arr0)
print("empty",'-'*30,)
arr1=np.empty((2,3))#创建一个2行3列的空数组
print(arr1)
print("zeros",'-'*30,)
arr2=np.zeros((2,3))#创建一个2行3列的零数组
print(arr2)
print("ones",'-'*30,)
arr3=np.ones((2,3),dtype=int)#创建一个2行3列的一数组
print(arr3)
print("full",'-'*30,)
arr4=np.full((2,3),5)#创建一个2行3列的5数组
print(arr4)
print("linspace",'-'*30,)

list to array ------------------------------
[1 2 3 4 5]
empty ------------------------------
[[2.5e-323 2.5e-323 2.5e-323]
 [2.5e-323 2.5e-323 2.5e-323]]
zeros ------------------------------
[[0. 0. 0.]
 [0. 0. 0.]]
ones ------------------------------
[[1 1 1]
 [1 1 1]]
full ------------------------------
[[5 5 5]
 [5 5 5]]
linspace ------------------------------
[10 12 15 17 20]
(5,)


In [57]:
arr5=np.linspace(10,20,5,dtype=int)#创建一个10到20的数组，包含5个元素
print("arr5:",arr5)
print("arr5的形状:",arr5.shape)
print("arr5的维度:",arr5.ndim)
print("arr5的元素类型:",arr5.dtype)
print("arr5的元素数量:",arr5.size)


arr5: [10 12 15 17 20]
arr5的形状: (5,)
arr5的维度: 1
arr5的元素类型: int64
arr5的元素数量: 5


In [62]:
#创建二维数组
print("二维数组")
arr6=np.arange(1,7).reshape(2,3)#创建一个2行3列的数组，元素从1到6
print(arr6)
print("arr6的形状:",arr6.shape)
print("arr6的维度:",arr6.ndim)
print("arr6的元素数量:",arr6.size)

#创建三维数组
print('-'*30)
print("三维数组")
arr7=np.arange(1,25).reshape(2,3,4)#创建一个2层3行4列的数组，元素从1到24
print(arr7)
print("arr7的形状:",arr7.shape)
print("arr7的维度:",arr7.ndim)
print("arr7的元素数量:",arr7.size)


二维数组
[[1 2 3]
 [4 5 6]]
arr6的形状: (2, 3)
arr6的维度: 2
arr6的元素数量: 6
------------------------------
三维数组
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[13 14 15 16]
  [17 18 19 20]
  [21 22 23 24]]]
arr7的形状: (2, 3, 4)
arr7的维度: 3
arr7的元素数量: 24


print("等间隔数组")
# arr8=np.arange(1,10,2)#创建一个1到9的数组，步长为2
#linspace()函数创建一个等间隔数组,间隔为(10-1)/4=2.5
#endpoint=False表示不包含10,True表示包含10,默认包含10
arr8=np.linspace(1,10,5,endpoint=False)#创建一个1到10的数组，包含5个元素，不包含10
print(arr8)


In [78]:
arr9=np.random.rand(2,3)#创建一个2行3列的随机数组
print(arr9)

[[0.72448207 0.32049697 0.73446427]
 [0.71941364 0.12135545 0.30126053]]


In [79]:
#标准正态分布随机数
arr10=np.random.randn(2,3)#创建一个2行3列的标准正态分布随机数组
print(arr10)

[[ 0.37389251  0.45788414 -0.79498197]
 [ 0.56379257  1.66737441  0.23760838]]


#### 改变形状

In [85]:
arr9=np.arange(0,12)
arr10=arr9.reshape(3,4)
print(arr9)
print("不改变原数组的形状,返回改变后的数组:")
print(arr10)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
不改变原数组的形状,返回改变后的数组:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
arr11=arr10+2# 每个元素都加2
print(arr11)

[[ 2  3  4  5]
 [ 6  7  8  9]
 [10 11 12 13]]


#### 索引和切片

In [97]:
arr12=np.arange(0,12).reshape(3,4)
print(arr12)
#取一行(下标为1的一行,也就是第二行)
print("取一行(下标为1的一行,也就是第二行):",arr12[1])
#取一列(下标为2的一列,也就是第三列)
print("取一列(下标为2的一列,也就是第三列):",arr12[:,2])
#取连续的行和列
print("取不连续的行和列:",arr12[0:2,0:2])
#取不连续的多行(不包括第2行和第3行)
print("取不连续的多行(不包括第2行和第3行):",arr12[[0,2],:])
#取不连续的多列(不包括第2列和第3列)
print("取不连续的多列(不包括第2列和第3列):",arr12[:,[0,3]])
#取从1开始的所有行
print("取从1开始的所有行:",arr12[1:,:])
#
# print("",arr12[:,:,2:])


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
取一行(下标为1的一行,也就是第二行): [4 5 6 7]
取一列(下标为2的一列,也就是第三列): [ 2  6 10]
取不连续的行和列: [[0 1]
 [4 5]]
取不连续的多行(不包括第2行和第3行): [[ 0  1  2  3]
 [ 8  9 10 11]]
取不连续的多列(不包括第2列和第3列): [[ 0  3]
 [ 4  7]
 [ 8 11]]
取从1开始的所有行: [[ 4  5  6  7]
 [ 8  9 10 11]]


#### 修改元素值

In [106]:
arr13 = np.arange(24).reshape(4, 6)  # 示例形状 (4, 6)
print("原始数组:")
print(arr13)
print('-' * 30)

# 1. 修改单值：将第2行第3列的值改为 999
arr13[1, 2] = 999
print("将第2行第3列的值改为 999,修改单值后:")
print(arr13)
print('-' * 30)

# 2. 修改某一行值：将第3行整行改为 [100, 101, 102, 103, 104, 105]
arr13[2, :] = np.array([100, 101, 102, 103, 104, 105])
print("将第3行整行改为 [100, 101, 102, 103, 104, 105],修改第3行后:")
print(arr13)
print('-' * 30)

# 3. 修改某一列值：将第4列整列改为 200
arr13[:, 3] = 200
print("将第4列整列改为 200,修改第4列后:")
print(arr13)
print('-' * 30)

# 4. 修改某一块值：将左上角 2×2 块改为 0
arr13[0:2, 0:2] = 0
print("将左上角2×2块改为 0,修改左上角2×2块后:")
print(arr13)
print('-' * 30)

# 5. 修改多个不相邻值：将 (0,1)、(2,3)、(3,5) 位置的值分别改为 77、88、99
rows = [0, 2, 3]
cols = [1, 3, 5]
vals = [77, 88, 99]
arr13[rows, cols] = vals
print("将 (0,1)、(2,3)、(3,5) 位置的值分别改为 77、88、99,修改多个不相邻值后:")
print(arr13)
print('-' * 30)

# 6. 根据条件修改：将所有大于 150 的值改为 -1
arr13[arr13 > 150] = -1
print("条件修改（>150→-1）后:")
print(arr13)
print('-' * 30)

# 7. 三目运算：将小于 100 的元素变为原来的两倍，否则减 50
arr13 = np.where(arr13 < 100, arr13 * 2, False)
print("三目运算后:")
print(arr13)
print('-' * 30)


原始数组:
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
------------------------------
将第2行第3列的值改为 999,修改单值后:
[[  0   1   2   3   4   5]
 [  6   7 999   9  10  11]
 [ 12  13  14  15  16  17]
 [ 18  19  20  21  22  23]]
------------------------------
将第3行整行改为 [100, 101, 102, 103, 104, 105],修改第3行后:
[[  0   1   2   3   4   5]
 [  6   7 999   9  10  11]
 [100 101 102 103 104 105]
 [ 18  19  20  21  22  23]]
------------------------------
将第4列整列改为 200,修改第4列后:
[[  0   1   2 200   4   5]
 [  6   7 999 200  10  11]
 [100 101 102 200 104 105]
 [ 18  19  20 200  22  23]]
------------------------------
将左上角2×2块改为 0,修改左上角2×2块后:
[[  0   0   2 200   4   5]
 [  0   0 999 200  10  11]
 [100 101 102 200 104 105]
 [ 18  19  20 200  22  23]]
------------------------------
将 (0,1)、(2,3)、(3,5) 位置的值分别改为 77、88、99,修改多个不相邻值后:
[[  0  77   2 200   4   5]
 [  0   0 999 200  10  11]
 [100 101 102  88 104 105]
 [ 18  19  20 200  22  99]]
------------------------------
条件修改（>150→-1